# Generated by Django 3.2.13 on 2023-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropage',
            name='image_sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heropage',
            name='image_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
