# Generated by Django 3.2.13 on 2023-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropage',
            name='user_content',
            field=models.PositiveIntegerField(choices=[(1, 'Left'), (2, 'Right')], default=1),
            preserve_default=False,
        ),
    ]
