# Generated by Django 3.2.13 on 2023-03-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_heropage_user_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=55)),
                ('subject', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
