# Generated by Django 3.2.13 on 2023-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heropage',
            name='image_sub_title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='heropage',
            name='image_title',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
