# Generated by Django 3.2.13 on 2023-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0004_auto_20230322_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
