# Generated by Django 3.2.13 on 2023-03-30 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Category Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Category Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category Description')),
                ('image', models.ImageField(default='default.jpeg', upload_to='category')),
                ('is_displayed_in_trending', models.BooleanField(default=False)),
                ('is_displayed_header', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('product_name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('slug', models.SlugField(verbose_name='Category Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Product Price')),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Discounted price')),
                ('image', models.ImageField(default='default.jpeg', upload_to='products')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Trending')),
                ('is_liked', models.BooleanField(default=False, verbose_name='You may Like')),
                ('background_color', models.CharField(default='#FF2020', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
