# Generated by Django 4.1.7 on 2023-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='trending'),
        ),
    ]
