# Generated by Django 3.2.13 on 2023-03-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230319_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_displayed_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_displayed_in_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
    ]
