# Generated by Django 3.2.13 on 2023-03-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230319_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='1', verbose_name='Category Slug'),
            preserve_default=False,
        ),
    ]
